# Generated by Django 2.1.5 on 2019-01-22 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('signature', models.BooleanField(default=False)),
                ('deposit', models.BooleanField(default=False)),
                ('tracking', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Recommanded',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=4, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='rate',
            name='recommanded',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colissimo.Recommanded'),
        ),
        migrations.AddField(
            model_name='rate',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colissimo.Region'),
        ),
    ]
